#!/bin/bash

# Usage check
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <interactsh-session-name>"
  exit 1
fi

# SSH host configuration
SSH_HOST="<youruser>@<yourhost>"

ssh -q -t "$SSH_HOST" "tmux list-windows -a | grep 'client-' |grep $1 | cut -d: -f1 | xargs -I {} tmux kill-window -t {} "

